version: "3"

networks:
  proxy:
    external: true

services:

  db:
    image: mdillon/postgis:10
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5480:5432"
    networks:
      - "proxy"
    volumes:
      - "$PWD/postgres-data:/var/lib/postgresql/data"

  geoserver:
    image: heitorcarneiro/geoserver:2.12.4
    restart: always
    volumes:
      - "$PWD/geoserver-data:/var/local/geoserver"
      - "$PWD/geoserver-logs:/usr/local/tomcat/logs"
    links:
      - "db:postgis"
    networks:
      - "proxy"
    depends_on:
      - "db"
